name: distribution-3
on:
  repository_dispatch:
    types:
      - manual-trigger
      - manual-trigger-distribution
      - manual-trigger-distribution-3
  schedule:
    - cron: '10 6 * * *'
jobs:
  run:
    services:
      distribution:
        image: quay.io/bloodorange/distribution:242c306b # TODO: use docker-provided image
    runs-on: ubuntu-latest
    steps:
      - name: Run OCI Distribution Spec conformance tests
        uses: opencontainers/distribution-spec@master
        env:
          OCI_ROOT_URL: http://distribution:5000
          OCI_NAMESPACE: oci-conformance/distribution-test
          OCI_TEST_CONTENT_DISCOVERY: 1
          OCI_HIDE_SKIPPED_WORKFLOWS: 1
      - name: Upload test report to S3
        run: aws s3 cp --acl public-read report.html s3://oci-conformance/distribution-spec/distribution/content-discovery/report.html
        if: always()
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_ACCESS_AWS_SECRET_ACCESS_KEY }}
